### ISSUE TITLE
bower_components directory structure changed from 0.0.4 to 0.0.6

### ISSUE THREAD

**Issue by JinpaLhawang** [c0bra/angular-responsive-images#7]
Hi there, we had our bower.json definition set to use "~0.0.4" and so when newer versions were pushed today, our builds started to fail. Our builds have been using "bower_components/angular-responsive-images/src/bh-responsive-images.js" however with the newer version (could have been with 0.0.5 or 0.0.6), this appears to have been changed to "bower_components/angular-responsive-images/js/bh-responsive-images.js".

To remedy this, we locked our version down to only use "0.0.4". The semver system otherwise believes a micro change to be non-breaking, whereas this directory change was breaking. Bumping to version "0.1.0" I believe would have identified this appropriately within the semver system and avoided build failures.

Was this directory change intended? We will likely upgrade our version of your library eventually and so wonder whether we should make a change to point to this new directory.

Thank you!
Nicholas

**Comment by c0bra** [comment]
Very sorry for the trouble. There were a lots of discrepancies between the configuration/project set-up and what was actually appearing in the releases. It's been several months since I cut a release and I was trying to get things all consistent. I should have foreseen changing the file location in bower as a breaking change and did not.

I can drop a 0.1.0 release but that won't solve the 0.0.5 / 0.0.6 commits from signifying the wrong thing. Is there a direction that would be most helpful to you?

**Comment by JinpaLhawang** [comment]
We are good as we are, locked down to 0.0.4. So, thinking out loud to address other users of the library, is it possible to change the directory structure back to using "src" instead of "js" and then cut a 0.0.7 release? That should fix any other users using "~0.0.4". Then you could revert that change back to being "js" and then cut a 0.1.0 release.

**Comment by c0bra** [comment]
Works for me.

**Comment by c0bra** [comment]
OK, should be good to go. There ended up being an 0.0.8 release because I'm bad at this. Let me know if there's any other issues.

**Comment by JinpaLhawang** [comment]
Verified that 0.0.8 works with the src path. Thank you so much for this and the fast turn-around. Was a pleasure working with you~
